---
title: "Embryo RNA DEAs"
author: "Leonard C. Steg"
date: '2025-07-15'
output: html_document
---

Read in pheno file with metadata
```{r}
pheno <- read.csv("Steg2026/EmbryoRNA/pheno.csv", row.names = 1)

pheno$Group <- as.factor(pheno$Group)
pheno$Mother <- as.factor(pheno$Mother)
```

Load function
```{r}
source("Steg2026/EmbryoRNA/scripts/dea.RNA.Embryo.R")
```

Run DEAs for full transcriptome, paternal and maternal transcriptomes. Use Mother as Covariate.
```{r}
dea.RNA.Embryo(pheno = pheno, stage = "TwoCell", genome = NULL,
                 VarExp = "Group", CovarBio = c("Mother"),
                 CtrGroup = "CTR", ExpGroup = "LPD", 
                 outputdir = "Steg2026/EmbryoRNA/results/03_dea/", suffix = "Basemodel_dedup_mother", 
                 salmondir = "Steg2026/EmbryoRNA/results/01_preprocess/10_salmon_post_dedup/")

dea.RNA.Embryo(pheno = pheno, stage = "TwoCell", genome = "genome1",
                 VarExp = "Group", CovarBio = c("Mother"), 
                 CtrGroup = "CTR", ExpGroup = "LPD", 
                 outputdir = "Steg2026/EmbryoRNA/results/03_dea/", suffix = "Basemodel_pat_mother", 
                 salmondir = "Steg2026/EmbryoRNA/results/01_preprocess/15_salmon_post_snpsplit/genome1/")

dea.RNA.Embryo(pheno = pheno, stage = "TwoCell", genome = "genome2",
                 VarExp = "Group", CovarBio = c("Mother"), 
                 CtrGroup = "CTR", ExpGroup = "LPD", 
                 outputdir = "Steg2026/EmbryoRNA/results/03_dea/", suffix = "Basemodel_mat_mother", 
                 salmondir = "Steg2026/EmbryoRNA/results/01_preprocess/15_salmon_post_snpsplit/genome2/")
```